// resources/js/Pages/Chats/Index.tsx
import { Chats, User } from "@/Types"
import ChatPreview from "@/Components/ChatPreview"
import { Head } from "@inertiajs/react"

type Props = {
    chats: Chats,
    user: User
}

function Index({ chats, user }: Props) {
    return (
        <>
            <Head title="Chats"/>

            <div>
                <div>
                    {chats.map(chat => (
                        <ChatPreview chat={chat} key={chat.id} />
                    ))}
                </div>
            </div>
        </>
    )
}

export default Index;

// resources/js/Pages/Chats/Index.svelte
<script context="module">
    export { default as layout } from '@/Layouts/HomeLayout.svelte'
</script>

<script lang="ts">
    import ChatPreview from '@/Components/ChatPreview.svelte';
    import type { Chats } from '@/Types';

    export let chats: Chats;
</script>

<div>
    {#each chats as chat}
        <ChatPreview {chat} />
    {/each}
</div>
